In [7]:
import yfinance as yf

In [8]:
apple = yf.Ticker("AAPL")
hist = apple.history(period="1mo")
print(hist)

# Or download data for a specific date range
msft_data = yf.download("MSFT", start="2025-01-01", end="2026-01-01")
print(msft_data.head())

[*********************100%***********************]  1 of 1 completed

                                 Open        High         Low       Close  \
Date
2026-05-11 00:00:00-04:00  291.980011  293.880005  290.230011  292.679993
2026-05-12 00:00:00-04:00  292.559998  295.269989  292.559998  294.799988
2026-05-13 00:00:00-04:00  293.500000  300.920013  293.500000  298.869995
2026-05-14 00:00:00-04:00  299.820007  300.450012  295.380005  298.209991
2026-05-15 00:00:00-04:00  297.899994  303.200012  296.519989  300.230011
2026-05-18 00:00:00-04:00  300.239990  300.660004  294.910004  297.839996
2026-05-19 00:00:00-04:00  296.970001  300.510010  296.350006  298.970001
2026-05-20 00:00:00-04:00  298.179993  302.799988  298.079987  302.250000
2026-05-21 00:00:00-04:00  301.059998  305.540009  300.399994  304.989990
2026-05-22 00:00:00-04:00  306.119995  311.399994  305.839996  308.820007
2026-05-26 00:00:00-04:00  309.559998  311.820007  307.670013  308.329987
2026-05-27 00:00:00-04:00  308.329987  313.260010  308.299988  310.850006
2026-05-28 00:00:00-04:00  310.679993  312.799988  309.570007  312.510010
2026-05-29 00:00:00-04:00  311.779999  315.000000  309.529999  312.059998
2026-06-01 00:00:00-04:00  309.630005  310.940002  305.019989  306.309998
2026-06-02 00:00:00-04:00  307.459991  315.450012  306.690002  315.200012
2026-06-03 00:00:00-04:00  314.179993  316.940002  308.850006  310.260010
2026-06-04 00:00:00-04:00  313.230011  313.540009  309.649994  311.230011
2026-06-05 00:00:00-04:00  312.859985  315.170013  307.149994  307.339996
2026-06-08 00:00:00-04:00  308.739990  317.399994  301.170013  301.540009
2026-06-09 00:00:00-04:00  300.279999  300.750000  287.779999  290.549988
2026-06-10 00:00:00-04:00  290.765015  294.744995  287.380005  291.579987

                             Volume  Dividends  Stock Splits
Date
2026-05-11 00:00:00-04:00  42247300       0.27           0.0
2026-05-12 00:00:00-04:00  45748100       0.00           0.0
2026-05-13 00:00:00-04:00  52684300       0.00           0.0
2026-05-14 00:00:00-04:00  35324900       0.00           0.0
2026-05-15 00:00:00-04:00  54862800       0.00           0.0
2026-05-18 00:00:00-04:00  34483000       0.00           0.0
2026-05-19 00:00:00-04:00  42243600       0.00           0.0
2026-05-20 00:00:00-04:00  38229800       0.00           0.0
2026-05-21 00:00:00-04:00  42965100       0.00           0.0
2026-05-22 00:00:00-04:00  43670200       0.00           0.0
2026-05-26 00:00:00-04:00  48000500       0.00           0.0
2026-05-27 00:00:00-04:00  50430900       0.00           0.0
2026-05-28 00:00:00-04:00  48220400       0.00           0.0
2026-05-29 00:00:00-04:00  70026800       0.00           0.0
2026-06-01 00:00:00-04:00  48849900       0.00           0.0
2026-06-02 00:00:00-04:00  44534700       0.00           0.0
2026-06-03 00:00:00-04:00  50836700       0.00           0.0
2026-06-04 00:00:00-04:00  44869100       0.00           0.0
2026-06-05 00:00:00-04:00  65310500       0.00           0.0
2026-06-08 00:00:00-04:00  77949100       0.00           0.0
2026-06-09 00:00:00-04:00  70024200       0.00           0.0
2026-06-10 00:00:00-04:00  49237715       0.00           0.0
Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-01-02  413.672607  421.074816  409.986357  420.541139  16896500
2025-01-03  418.386719  419.058739  414.621389  416.143313  16662900
2025-01-06  422.833954  429.228102  420.491744  422.982189  20573600
2025-01-07  417.418213  425.601139  415.866612  423.970489  18139100
2025-01-08  419.582520  421.964269  416.597936  418.495410  15054600

In [9]:
dat = yf.Ticker("AAPL")
dat.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 290.55,
 'open': 290.765,
 'dayLow': 287.38,
 'dayHigh': 294.745,
 'regularMarketPreviousClose': 290.55,
 'regularMarketOpen': 290.765,
 'regularMarketDayLow': 287.38,
 'regularMarketDayHigh': 294.745,
 'dividendRate': 1.08,
 'dividendYield': 0.37,
 'exDividendDate': 1778457600,
 'payoutRatio': 0.1259,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.086,
 'trailingPE': 35.34303,
 'forwardPE': 30.394382,
 'volume': 49237715,
 'regularMarketVolume': 49237715,
 'averageVolume': 45829400,
 'averageVolume10days': 54902860,
 'averageDailyVolume10Day': 54902860,
 'bid': 292.11,
 'ask': 291.94,
 'bidSize': 3,
 'askSize': 1,
 'marketCap': 4282539048960,
 'nonDilutedMarketCap': 4267411285800,
 'fiftyTwoWeekLow': 195.07,
 'fiftyTwoWeekHigh': 317.4,
 'allTimeHigh': 317.4,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.486355,
 'fiftyDayAverage': 282.2104,
 'twoHundredDayAverage': 265.57074,
 'trailingAnnualDividendRate': 1.04,
 'trailingAnnualDividendYield': 0.0035794184,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4298743218176,
 'profitMargins': 0.27152002,
 'floatShares': 14662534368,
 'sharesOutstanding': 14687356000,
 'sharesShort': 155886024,
 'sharesShortPriorMonth': 134675274,
 'sharesShortPreviousMonthDate': 1777507200,
 'dateShortInterest': 1780012800,
 'sharesPercentSharesOut': 0.0106,
 'heldPercentInsiders': 0.01632,
 'heldPercentInstitutions': 0.65830004,
 'shortRatio': 3.12,
 'shortPercentOfFloat': 0.0106,
 'impliedSharesOutstanding': 14687356000,
 'bookValue': 7.26,
 'priceToBook': 40.162533,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1774656000,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 122575003648,
 'trailingEps': 8.25,
 'forwardEps': 9.59322,
 'pegRatio': 2.42,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.522,
 'enterpriseToEbitda': 26.871,
 '52WeekChange': 0.51695347,
 'SandP52WeekChange': 0.22973013,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1778457600,
 'quoteType': 'EQUITY',
 'currentPrice': 291.58,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 312.48373,
 'targetMedianPrice': 310.0,
 'recommendationMean': 1.97917,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 43,
 'totalCash': 68507000832,
 'totalCashPerShare': 4.664,
 'ebitda': 159975997440,
 'totalDebt': 84710998016,
 'quickRatio': 0.906,
 'currentRatio': 1.07,
 'totalRevenue': 451442016256,
 'debtToEquity': 79.548,
 'revenuePerShare': 30.534,
 'returnOnAssets': 0.26229,
 'returnOnEquity': 1.4147099,
 'grossProfits': 216070995968,
 'freeCashflow': 101090746368,
 'operatingCashflow': 140222005248,
 'earningsGrowth': 0.218,
 'revenueGrowth': 0.166,
 'grossMargins': 0.47862,
 'ebitdaMargins': 0.35437,
 'operatingMargins': 0.32275,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'regularMarketChangePercent': 0.3545,
 'regularMarketPrice': 291.58,
 'shortName': 'Apple Inc.',
 'regularMarketDayRange': '287.38 - 294.745',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 45829400,
 'fiftyTwoWeekLowChange': 96.50998,
 'fiftyTwoWeekLowChangePercent': 0.49474534,
 'fiftyTwoWeekRange': '195.07 - 317.4',
 'fiftyTwoWeekHighChange': -25.820007,
 'fiftyTwoWeekHighChangePercent': -0.08134848,
 'fiftyTwoWeekChangePercent': 51.695347,
 'dividendDate': 1778716800,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1785441600,
 'earningsTimestampEnd': 1785441600,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 8.25,
 'epsForward': 9.59322,
 'epsCurrentYear': 8.74906,
 'priceEpsCurrentYear': 33.327007,
 'fiftyDayAverageChange': 9.369598,
 'fiftyDayAverageChangePercent': 0.033200756,
 'twoHundredDayAverageChange': 26.009247,
 'twoHundredDayAverageChangePercent': 0.097937174,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'marketState': 'POSTPOST',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': -0.25851712,
 'postMarketPrice': 290.8262,
 'postMarketChange': -0.7537842,
 'regularMarketChange': 1.03,
 'longName': 'Apple Inc.',
 'corporateActions': [],
 'postMarketTime': 1781135999,
 'regularMarketTime': 1781121601,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'displayName': 'Apple',
 'trailingPegRatio': 2.3354}

In [10]:
dat.calendar

{'Dividend Date': datetime.date(2026, 5, 14),
 'Ex-Dividend Date': datetime.date(2026, 5, 11),
 'Earnings Date': [datetime.date(2026, 7, 31)],
 'Earnings High': 1.99,
 'Earnings Low': 1.83,
 'Earnings Average': 1.89541,
 'Revenue High': 112168000000,
 'Revenue Low': 107501000000,
 'Revenue Average': 109023320870}

In [11]:
dat.analyst_price_targets

{'current': 291.58,
 'high': 400.0,
 'low': 215.0,
 'mean': 312.48373,
 'median': 310.0}

In [12]:
dat.quarterly_income_stmt

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.750000e-01,1.750000e-01,1.627240e-01,1.640000e-01,1.545550e-01
Normalized EBITDA,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10
Net Income From Continuing Operation Net Minority Interest,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Reconciled Depreciation,3.439000e+09,3.214000e+09,3.127000e+09,2.830000e+09,2.661000e+09
Reconciled Cost Of Revenue,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10
EBITDA,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10
EBIT,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Normalized Income,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income From Continuing And Discontinued Operation,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Total Expenses,7.529900e+10,9.290400e+10,7.003900e+10,6.583400e+10,6.577000e+10
Total Operating Income As Reported,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Diluted Average Shares,1.472587e+10,1.481036e+10,1.486361e+10,1.494818e+10,1.505613e+10
Basic Average Shares,1.467328e+10,1.474816e+10,1.481531e+10,1.490289e+10,1.499408e+10
Diluted EPS,2.010000e+00,2.840000e+00,1.850000e+00,1.570000e+00,1.650000e+00
Basic EPS,2.020000e+00,2.850000e+00,1.850000e+00,1.570000e+00,1.650000e+00
Diluted NI Availto Com Stockholders,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Common Stockholders,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Including Noncontrolling Interests,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Continuous Operations,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Tax Provision,6.255000e+09,8.905000e+09,5.338000e+09,4.597000e+09,4.530000e+09
Pretax Income,3.583300e+10,5.100200e+10,3.280400e+10,2.803100e+10,2.931000e+10
Other Income Expense,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08
Other Non Operating Income Expenses,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08
Operating Income,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Operating Expense,1.889600e+10,1.837900e+10,1.591400e+10,1.551600e+10,1.527800e+10
Research And Development,1.141900e+10,1.088700e+10,8.866000e+09,8.866000e+09,8.550000e+09
Selling General And Administration,7.477000e+09,7.492000e+09,7.048000e+09,6.650000e+09,6.728000e+09
Gross Profit,5.478100e+10,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10
Cost Of Revenue,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10
Total Revenue,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10
Operating Revenue,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10

In [13]:
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-05-11 00:00:00-04:00,291.980011,293.880005,290.230011,292.679993,42247300,0.27,0.0
2026-05-12 00:00:00-04:00,292.559998,295.269989,292.559998,294.799988,45748100,0.00,0.0
2026-05-13 00:00:00-04:00,293.500000,300.920013,293.500000,298.869995,52684300,0.00,0.0
2026-05-14 00:00:00-04:00,299.820007,300.450012,295.380005,298.209991,35324900,0.00,0.0
2026-05-15 00:00:00-04:00,297.899994,303.200012,296.519989,300.230011,54862800,0.00,0.0
2026-05-18 00:00:00-04:00,300.239990,300.660004,294.910004,297.839996,34483000,0.00,0.0
2026-05-19 00:00:00-04:00,296.970001,300.510010,296.350006,298.970001,42243600,0.00,0.0
2026-05-20 00:00:00-04:00,298.179993,302.799988,298.079987,302.250000,38229800,0.00,0.0
2026-05-21 00:00:00-04:00,301.059998,305.540009,300.399994,304.989990,42965100,0.00,0.0
2026-05-22 00:00:00-04:00,306.119995,311.399994,305.839996,308.820007,43670200,0.00,0.0
2026-05-26 00:00:00-04:00,309.559998,311.820007,307.670013,308.329987,48000500,0.00,0.0
2026-05-27 00:00:00-04:00,308.329987,313.260010,308.299988,310.850006,50430900,0.00,0.0
2026-05-28 00:00:00-04:00,310.679993,312.799988,309.570007,312.510010,48220400,0.00,0.0
2026-05-29 00:00:00-04:00,311.779999,315.000000,309.529999,312.059998,70026800,0.00,0.0
2026-06-01 00:00:00-04:00,309.630005,310.940002,305.019989,306.309998,48849900,0.00,0.0
2026-06-02 00:00:00-04:00,307.459991,315.450012,306.690002,315.200012,44534700,0.00,0.0
2026-06-03 00:00:00-04:00,314.179993,316.940002,308.850006,310.260010,50836700,0.00,0.0
2026-06-04 00:00:00-04:00,313.230011,313.540009,309.649994,311.230011,44869100,0.00,0.0
2026-06-05 00:00:00-04:00,312.859985,315.170013,307.149994,307.339996,65310500,0.00,0.0
2026-06-08 00:00:00-04:00,308.739990,317.399994,301.170013,301.540009,77949100,0.00,0.0
2026-06-09 00:00:00-04:00,300.279999,300.750000,287.779999,290.549988,70024200,0.00,0.0
2026-06-10 00:00:00-04:00,290.765015,294.744995,287.380005,291.579987,49237715,0.00,0.0

In [14]:
dat.option_chain(dat.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260612C00125000,2026-06-10 19:24:16+00:00,125.0,167.09,165.65,168.10,-10.220001,-5.763917,224,8,5.074222,True,REGULAR,USD
1,AAPL260612C00130000,2026-06-10 19:24:16+00:00,130.0,162.19,160.20,163.00,-10.130005,-5.878601,221,8,3.625001,True,REGULAR,USD
2,AAPL260612C00145000,2026-06-10 19:12:31+00:00,145.0,148.06,145.15,148.05,1.750000,1.196090,139,19,3.171877,True,REGULAR,USD
3,AAPL260612C00150000,2026-06-10 18:41:33+00:00,150.0,143.74,140.10,143.45,3.000000,2.131590,8,11,3.843750,True,REGULAR,USD
4,AAPL260612C00155000,2026-06-05 17:43:40+00:00,155.0,156.78,135.10,138.45,0.000000,0.000000,92,15,3.671876,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,AAPL260612C00380000,2026-06-09 17:44:51+00:00,380.0,0.02,0.00,0.45,0.000000,0.000000,3,542,1.658205,False,REGULAR,USD
60,AAPL260612C00385000,2026-06-08 18:47:21+00:00,385.0,0.02,0.00,0.45,0.000000,0.000000,7,31,1.726564,False,REGULAR,USD
61,AAPL260612C00390000,2026-06-08 14:01:03+00:00,390.0,0.01,0.00,0.45,0.000000,0.000000,1,48,1.794923,False,REGULAR,USD
62,AAPL260612C00395000,2026-06-05 19:59:48+00:00,395.0,0.01,0.00,0.01,0.000000,0.000000,10,839,1.250004,False,REGULAR,USD
63,AAPL260612C00400000,2026-06-08 17:37:39+00:00,400.0,0.01,0.00,0.01,0.000000,0.000000,25,720,1.312503,False,REGULAR,USD

In [15]:
dat.financials

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [16]:
dat.quarterly_financials

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.750000e-01,1.750000e-01,1.627240e-01,1.640000e-01,1.545550e-01
Normalized EBITDA,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10
Net Income From Continuing Operation Net Minority Interest,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Reconciled Depreciation,3.439000e+09,3.214000e+09,3.127000e+09,2.830000e+09,2.661000e+09
Reconciled Cost Of Revenue,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10
EBITDA,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10
EBIT,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Normalized Income,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income From Continuing And Discontinued Operation,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Total Expenses,7.529900e+10,9.290400e+10,7.003900e+10,6.583400e+10,6.577000e+10
Total Operating Income As Reported,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Diluted Average Shares,1.472587e+10,1.481036e+10,1.486361e+10,1.494818e+10,1.505613e+10
Basic Average Shares,1.467328e+10,1.474816e+10,1.481531e+10,1.490289e+10,1.499408e+10
Diluted EPS,2.010000e+00,2.840000e+00,1.850000e+00,1.570000e+00,1.650000e+00
Basic EPS,2.020000e+00,2.850000e+00,1.850000e+00,1.570000e+00,1.650000e+00
Diluted NI Availto Com Stockholders,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Common Stockholders,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Including Noncontrolling Interests,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Net Income Continuous Operations,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10
Tax Provision,6.255000e+09,8.905000e+09,5.338000e+09,4.597000e+09,4.530000e+09
Pretax Income,3.583300e+10,5.100200e+10,3.280400e+10,2.803100e+10,2.931000e+10
Other Income Expense,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08
Other Non Operating Income Expenses,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08
Operating Income,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10
Operating Expense,1.889600e+10,1.837900e+10,1.591400e+10,1.551600e+10,1.527800e+10
Research And Development,1.141900e+10,1.088700e+10,8.866000e+09,8.866000e+09,8.550000e+09
Selling General And Administration,7.477000e+09,7.492000e+09,7.048000e+09,6.650000e+09,6.728000e+09
Gross Profit,5.478100e+10,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10
Cost Of Revenue,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10
Total Revenue,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10
Operating Revenue,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10

In [17]:
dat.balance_sheet

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Treasury Shares Number,NaN,NaN,0.000000e+00,NaN,NaN
Ordinary Shares Number,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Share Issued,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Net Debt,6.272300e+10,7.668600e+10,8.112300e+10,9.642300e+10,NaN
Total Debt,9.865700e+10,1.066290e+11,1.110880e+11,1.324800e+11,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,5.469700e+10,6.517100e+10,6.155500e+10,4.830400e+10,NaN
Other Short Term Investments,1.876300e+10,3.522800e+10,3.159000e+10,2.465800e+10,NaN
Cash And Cash Equivalents,3.593400e+10,2.994300e+10,2.996500e+10,2.364600e+10,NaN
Cash Equivalents,7.667000e+09,2.744000e+09,1.606000e+09,5.100000e+09,NaN
Cash Financial,2.826700e+10,2.719900e+10,2.835900e+10,1.854600e+10,NaN

In [18]:
dat.cashflow

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Free Cash Flow,9.876700e+10,1.088070e+11,9.958400e+10,1.114430e+11,NaN
Repurchase Of Capital Stock,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
Repayment Of Debt,-1.093200e+10,-9.958000e+09,-1.115100e+10,-9.543000e+09,NaN
Issuance Of Debt,4.481000e+09,0.000000e+00,5.228000e+09,5.465000e+09,NaN
Issuance Of Capital Stock,NaN,NaN,NaN,NaN,1.105000e+09
Capital Expenditure,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
Interest Paid Supplemental Data,NaN,NaN,3.803000e+09,2.865000e+09,2.687000e+09
Income Tax Paid Supplemental Data,4.336900e+10,2.610200e+10,1.867900e+10,1.957300e+10,NaN
End Cash Position,3.593400e+10,2.994300e+10,3.073700e+10,2.497700e+10,NaN
Beginning Cash Position,2.994300e+10,3.073700e+10,2.497700e+10,3.592900e+10,NaN
Changes In Cash,5.991000e+09,-7.940000e+08,5.760000e+09,-1.095200e+10,NaN
Financing Cash Flow,-1.206860e+11,-1.219830e+11,-1.084880e+11,-1.107490e+11,NaN
Cash Flow From Continuing Financing Activities,-1.206860e+11,-1.219830e+11,-1.084880e+11,-1.107490e+11,NaN
Net Other Financing Charges,-6.071000e+09,-5.802000e+09,-6.012000e+09,-6.383000e+09,NaN
Cash Dividends Paid,-1.542100e+10,-1.523400e+10,-1.502500e+10,-1.484100e+10,NaN
Common Stock Dividend Paid,-1.542100e+10,-1.523400e+10,-1.502500e+10,-1.484100e+10,NaN
Net Common Stock Issuance,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
Common Stock Payments,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
Common Stock Issuance,NaN,NaN,NaN,NaN,1.105000e+09
Net Issuance Payments Of Debt,-8.483000e+09,-5.998000e+09,-9.901000e+09,-1.230000e+08,NaN
Net Short Term Debt Issuance,-2.032000e+09,3.960000e+09,-3.978000e+09,3.955000e+09,NaN
Net Long Term Debt Issuance,-6.451000e+09,-9.958000e+09,-5.923000e+09,-4.078000e+09,NaN
Long Term Debt Payments,-1.093200e+10,-9.958000e+09,-1.115100e+10,-9.543000e+09,NaN
Long Term Debt Issuance,4.481000e+09,0.000000e+00,5.228000e+09,5.465000e+09,NaN
Investing Cash Flow,1.519500e+10,2.935000e+09,3.705000e+09,-2.235400e+10,NaN
Cash Flow From Continuing Investing Activities,1.519500e+10,2.935000e+09,3.705000e+09,-2.235400e+10,NaN
Net Other Investing Changes,-1.480000e+09,-1.308000e+09,-1.337000e+09,-2.086000e+09,NaN
Net Investment Purchase And Sale,2.939000e+10,1.369000e+10,1.600100e+10,-9.560000e+09,NaN
Sale Of Investment,5.379700e+10,6.234600e+10,4.551400e+10,6.736300e+10,NaN
Purchase Of Investment,-2.440700e+10,-4.865600e+10,-2.951300e+10,-7.692300e+10,NaN
Net Business Purchase And Sale,NaN,NaN,NaN,-3.060000e+08,-3.300000e+07
Purchase Of Business,NaN,NaN,NaN,-3.060000e+08,-3.300000e+07
Net PPE Purchase And Sale,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
Purchase Of PPE,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
Operating Cash Flow,1.114820e+11,1.182540e+11,1.105430e+11,1.221510e+11,NaN
Cash Flow From Continuing Operating Activities,1.114820e+11,1.182540e+11,1.105430e+11,1.221510e+11,NaN
Change In Working Capital,-2.500000e+10,3.651000e+09,-6.577000e+09,1.200000e+09,NaN
Change In Other Working Capital,NaN,NaN,NaN,4.780000e+08,1.676000e+09
Change In Other Current Liabilities,-1.107600e+10,1.555200e+10,3.031000e+09,6.110000e+09,NaN
Change In Other Current Assets,-9.197000e+09,-1.173100e+10,-5.684000e+09,-6.499000e+09,NaN
Change In Payables And Accrued Expense,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
Change In Payable,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
Change In Account Payable,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
Change In Inventory,1.400000e+09,-1.046000e+09,-1.618000e+09,1.484000e+09,NaN
Change In Receivables,-7.029000e+09,-5.144000e+09,-4.170000e+08,-9.343000e+09,NaN
Changes In Account Receivables,-6.682000e+09,-3.788000e+09,-1.688000e+09,-1.823000e+09,NaN
Other Non Cash Items,-8.900000e+07,-2.266000e+09,-2.227000e+09,1.006000e+09,NaN
Stock Based Compensation,1.286300e+10,1.168800e+10,1.083300e+10,9.038000e+09,NaN
Deferred Tax,NaN,NaN,NaN,8.950000e+08,-4.774000e+09
Deferred Income Tax,NaN,NaN,NaN,8.950000e+08,-4.774000e+09
Depreciation Amortization Depletion,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Depreciation And Amortization,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Net Income From Continuing Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN